# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMailboxMailbox',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField()),
                ('last_polling', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_mailbox_mailbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMailboxMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('from_header', models.CharField(max_length=255)),
                ('to_header', models.TextField()),
                ('outgoing', models.BooleanField()),
                ('body', models.TextField()),
                ('encoded', models.BooleanField()),
                ('processed', models.DateTimeField()),
                ('read', models.DateTimeField(blank=True, null=True)),
                ('eml', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_mailbox_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMailboxMessageattachment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('headers', models.TextField(blank=True, null=True)),
                ('document', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_mailbox_messageattachment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prioritaet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.EmailField(blank=True, help_text='Who should get a notification if ticket is done?? ', max_length=254, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('progress', models.CharField(blank=True, max_length=255, null=True)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.datetime(2018, 1, 3, 14, 47, 39, 372530, tzinfo=utc), editable=False)),
                ('prioritaet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Prioritaet')),
            ],
            options={
                'ordering': ['prioritaet'],
            },
        ),
    ]
