# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20180122_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 1, 22, 12, 6, 57, 26874, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='progress',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
