# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20180122_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 1, 22, 12, 52, 10, 655993, tzinfo=utc), editable=False),
        ),
    ]
