# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20180122_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 1, 24, 11, 24, 59, 532387, tzinfo=utc), editable=False),
        ),
    ]
