# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20180124_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 1, 24, 12, 49, 14, 568092, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ticket.models.file_upload_path),
        ),
    ]
