# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20180124_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 2, 14, 7, 38, 55, 434442, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
