# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20180214_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['done', 'prioritaet', '-created_at']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 7, 42, 22, 754590), editable=False),
        ),
    ]
