# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20180226_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 26, 8, 8, 28), null=True),
        ),
    ]
