# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20180226_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
