# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_auto_20180315_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ticket.models.file_upload_path),
        ),
    ]
