# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('ticket', '0015_auto_20180404_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
    ]
